server.port: 8083


logging:
  config: classpath:logback.groovy
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

minio:
  bucket: '842b2f64-b544-422c-86ea-803d75ccb4c9'
  key: Q3AM3UQ867SPQQA43P2F
  secret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  url: https://play.minio.io:9000
